#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Mar 20 17:06:25 2018

@author: tensorflow-cuda
"""
import numpy as np
import cv2
cap = cv2.VideoCapture('rtsp://admin:kgisl@123@10.100.10.192/doc/page/preview.asp')
winName = "Movement Indicator"		    # comment to hide window
cv2.namedWindow(winName)


ret = True
while (ret):
    ret, img = cap.read()
    cv2.imshow('image',cv2.resize(img,(1280,960)))
    key = cv2.waitKey(10)
    if key == 27:
        cv2.destroyWindow(winName)			# comment to hide window
        break
